import StyledComponentsRegistry from "@/lib/registry";
import '../styles/globals.css';
import { GlobalStyle } from "@/styles/global";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Portifólio RFL",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Ou "/icone-novo.png"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <StyledComponentsRegistry>
          <GlobalStyle />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
